Repository dassana-io/dassana, pull requests merged in 2021-11, with the labels that each got.

#480 enhancement: GuardDuty vendor severity
  content/actions/gd-via-sh/README.md
  content/actions/gd-via-sh/src/gd_handler.py
  content/actions/gd-via-sh/src/test_handler_gd.py
Labels: enhancement

#481 documentation: Added vendor severity to example normalizer output
  docs-root/docs/getting-started/concepts/normalization.md
Labels: documentation

#479 enhancement: AWS-Config vendor severity
  content/actions/aws-config-via-sh/README.md
  content/actions/aws-config-via-sh/src/ac_handler.py
  content/actions/aws-config-via-sh/src/test_handler_ac.py
Labels: enhancement

#486 Linter & Error Messaging Upgrades / Fixes - #411
  .dassana-internal-devops/scripts/validate-id-patterns.py
  .github/workflows/lint-content.yaml
  content/actions/aws-config-via-sh/README.md
  content/actions/aws-config-via-sh/src/ac_handler.py
  content/actions/aws-config-via-sh/src/test_handler_ac.py
  content/actions/gd-via-sh/README.md
  content/actions/gd-via-sh/src/gd_handler.py
  content/actions/gd-via-sh/src/test_handler_gd.py
  content/schemas/base-workflow-schema.json
  content/workflows/csp/aws/service/iam/resources/user/resource-context/user-context.yaml
  engine/src/main/java/app/dassana/core/api/WorkflowValidator.java
  engine/src/main/java/app/dassana/core/risk/eval/RiskEvaluator.java
  engine/src/main/java/app/dassana/core/risk/model/Risk.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
  engine/src/test/resources/inputs/validSecurityHubAlert-response-with-input.json
  engine/src/test/resources/inputs/validSecurityHubAlert-response.json
Labels: enhancement

#506 fix(#505) - Output vendor severity in normalizers
  content/workflows/vendors/aws-config/aws-config-via-security-hub.yaml
  content/workflows/vendors/aws-config/aws-config.yaml
  content/workflows/vendors/foo-cloud/normalize.yaml
  content/workflows/vendors/guardduty/guardduty-via-securityhub.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: bug

#463 389 - added sub-rules, match most severe, and better error message when condition isn't correct.
  .gitignore
  content/pkg/build.sh
  content/schemas/base-workflow-schema.json
  content/schemas/risk-schema.json
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
  content/workflows/csp/aws/service/iam/resources/user/resource-context/user-context.yaml
  engine/src/main/java/app/dassana/core/api/WorkflowValidator.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/contentmanager/Parser.java
  engine/src/main/java/app/dassana/core/risk/eval/RiskEvaluator.java
  engine/src/main/java/app/dassana/core/risk/model/Risk.java
  engine/src/main/java/app/dassana/core/risk/model/Rule.java
  engine/src/main/java/app/dassana/core/risk/model/SubRule.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/test/java/app/dassana/core/restapi/Common.java
  engine/src/test/java/app/dassana/core/restapi/RunTest.groovy
  engine/src/test/resources/inputs/validGDAlertWithSubRules-response-with-input.json
  engine/src/test/resources/inputs/validGDAlertWithSubRules-response.json
  engine/src/test/resources/inputs/validGDAlertWithSubRules.json
  engine/src/test/resources/inputs/validSecurityHubAlert-response-with-input.json
  engine/src/test/resources/inputs/validSecurityHubAlert-response.json
  engine/src/test/resources/responses/ec2-exposure.json
  engine/src/test/resources/responses/gd-normalization.json
  engine/src/test/resources/responses/lookup.json
  engine/src/test/resources/responses/risky-permissions.json
Labels: enhancement

#508 Doc updates
  docs-root/docs/getting-started/installation.mdx
  docs-root/docs/guides/ops/backup.md
  docs-root/docs/guides/ops/monitoring.md
  docs-root/docs/guides/ops/troubleshooting.md
  docs-root/sidebars.js
Labels: documentation

#507 Postman API Testing
  .github/workflows/publish-cft.yaml
  engine/api/README.md
  engine/api/api.postman_collection.json
  engine/api/env.postman_environment.json
Labels: feature

#510 Hide header
  .github/workflows/publish-cft.yaml
Labels: bug

#511 Set tag in build action
  .github/workflows/publish-cft.yaml
Labels: bug

#513 chore: update normalizer ReadMes
  .gitignore
  content/actions/README.md
  content/actions/aws-config-via-sh/README.md
  content/actions/gd-via-sh/README.md
  content/actions/prisma-cloud-normalizer/README.md
Labels: chore

#512 enhancement: bucket stats unit tests
  content/actions/get-bucket-stats/handler_bucket_stats.py
  content/actions/get-bucket-stats/test_bucket_stats.py
  content/pkg/template.yaml
Labels: enhancement

#515 AWS Review updates
  content/pkg/template.yaml
  docs-root/docs/guides/action-authoring/action.mdx
  docs-root/docs/how-it-works/low-level.mdx
  engine/src/main/java/app/dassana/core/client/infra/S3Store.java
Labels: chore

#516 cleanup: cleanup github actions
  .dassana-internal-devops/scripts/validate-rule-grammar.py
  .dassana-internal-devops/scripts/validate-workflow-steps.py
  .github/workflows/lint-content.yaml
Labels: chore

#518 Cloudsplaining Blog Article
  docs-root/blog/2021-11-11-cloudsplaining.md
Labels: documentation

#514 enhancement: Normalized Alert Time
  content/actions/aws-config-via-sh/README.md
  content/actions/aws-config-via-sh/src/ac_handler.py
  content/actions/aws-config-via-sh/src/test_handler_ac.py
  content/actions/aws-config-via-sh/tests/examples/apigateway_eb.json
  content/actions/gd-via-sh/README.md
  content/actions/gd-via-sh/src/gd_handler.py
  content/actions/gd-via-sh/src/test_handler_gd.py
  content/actions/normalizer-lookup/test_normalizer_lookup.py
  content/actions/prisma-cloud-normalizer/README.md
  content/actions/prisma-cloud-normalizer/src/handler_prisma_cloud.py
  content/actions/prisma-cloud-normalizer/src/test_handler_prisma_cloud.py
  content/pkg/deps/python/dassana/common/models.py
  content/pkg/deps/python/dassana/common/timing.py
  content/workflows/vendors/aws-config/aws-config-via-security-hub.yaml
  content/workflows/vendors/foo-cloud/normalize.yaml
  content/workflows/vendors/guardduty/guardduty-via-securityhub.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: enhancement

#523 Add step-security/harden-runner to workflow
  .github/workflows/publish-ut-coverage.yaml
Labels: chore

#517 Alert api + postman tests
  engine/api/api.postman_collection.json
  engine/src/main/java/app/dassana/core/client/infra/S3Store.java
  engine/src/main/java/app/dassana/core/contentmanager/infra/S3WorkflowManager.java
  engine/src/main/java/app/dassana/core/restapi/Alert.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/test/java/app/dassana/core/restapi/Common.java
  engine/src/test/java/app/dassana/core/restapi/RunTest.groovy
  engine/src/test/resources/inputs/alert-from-s3.json
  engine/src/test/resources/inputs/validGDAlertWithSubRules-response-with-input.json
  engine/src/test/resources/inputs/validGDAlertWithSubRules-response.json
  engine/src/test/resources/inputs/validSecurityHubAlert-response-with-input.json
  engine/src/test/resources/inputs/validSecurityHubAlert-response.json
  engine/src/test/resources/responses/normalization.json
Labels: feature

#524 readme clarification
  content/actions/get-iam-policy-risks/README.md
Labels: chore

#527 enhancement: Normalized Alert Status
  content/actions/aws-config-via-sh/README.md
  content/actions/aws-config-via-sh/src/ac_handler.py
  content/actions/aws-config-via-sh/src/test_handler_ac.py
  content/actions/gd-via-sh/README.md
  content/actions/gd-via-sh/src/gd_handler.py
  content/actions/gd-via-sh/src/test_handler_gd.py
  content/actions/normalizer-lookup/test_normalizer_lookup.py
  content/actions/prisma-cloud-normalizer/README.md
  content/actions/prisma-cloud-normalizer/src/handler_prisma_cloud.py
  content/actions/prisma-cloud-normalizer/src/test_handler_prisma_cloud.py
  content/pkg/deps/python/dassana/common/models.py
  content/workflows/vendors/aws-config/aws-config-via-security-hub.yaml
  content/workflows/vendors/guardduty/guardduty-via-securityhub.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: enhancement

#533 GuardDuty Blog Article
  docs-root/blog/2021-11-18-guardduty.mdx
Labels: documentation
