Repository dassana-io/dassana, pull requests merged in 2021-08, with the labels that each got.

#4 Mapped PC IAM password policy and cloud trail bucket open policy
  content/workflows/policies/csp/aws/service/iam/resources/user/iam-password-policy-is-not-secure.yaml
  content/workflows/policies/csp/aws/service/s3/resources/bucket/bucket-is-public.yaml
  docs-root/src/css/custom.css
Labels: enhancement

#17 fix: Add permission to root bucket to DassanaEngineRole
  content/pkg/template.yaml
Labels: bug

#39 Docs - Update admonitions styles
  docs-root/src/css/custom.css
Labels: enhancement

#38 Cis 1.2 changes
  content/schemas/categories.yaml
  content/workflows/policies/csp/aws/service/iam/resources/policy/iam-policy-with-admin-access.yaml
  content/workflows/policies/csp/aws/service/iam/resources/policy/iam-role-not-enabled-for-ec2.yaml
  content/workflows/policies/csp/aws/service/iam/resources/policy/iam-support-role-exists.yaml
  content/workflows/policies/csp/aws/service/iam/resources/user/iam-user-policy-exists.yaml
  content/workflows/policies/csp/aws/service/iam/resources/user/user-has-console-and-access-keys.yaml
Labels: feature

#40 limit content linting to linting only
  .github/workflows/lint-content.yaml
Labels: chore

#42 Update README.md
  README.md
Labels: chore

#43 Update README.md
  .github/workflows/engine-unit-tests.yaml
  engine/README.md
Labels: chore

#44 Create publish-ut-coverage.yaml
  .github/workflows/publish-ut-coverage.yaml
Labels: chore

#45 Gha test 3
  .github/workflows/publish-public-policies-and-actions.yaml
  .github/workflows/verify-labels.yaml
  engine/README.md
Labels: chore

#47 Move risk calc action to the engine #46
  content/actions/risk-calc-action/README.md
  content/actions/risk-calc-action/dassana-action.yaml
  content/actions/risk-calc-action/pom.xml
  content/actions/risk-calc-action/src/main/java/app/dassana/action/Risk.java
  content/actions/risk-calc-action/src/main/java/app/dassana/action/Rule.java
  content/actions/risk-calc-action/src/test/java/app/dassana/action/RequestHandlerTest.java
  content/actions/risk-calc-action/src/test/resources/input.json
  content/actions/risk-calc-action/src/test/resources/logback.xml
  content/pkg/template.yaml
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/policycontext/RiskCalcActionRequest.java
  engine/src/main/java/app/dassana/core/policycontext/model/PolicyContext.java
  engine/src/main/java/app/dassana/core/resource/model/GeneralContext.java
  engine/src/main/java/app/dassana/core/resource/model/RiskWithWorkflowOutput.java
  engine/src/main/java/app/dassana/core/risk/eval/RiskEvalRequest.java
  engine/src/main/java/app/dassana/core/risk/eval/RiskEvaluator.java
  engine/src/main/java/app/dassana/core/risk/model/CombinedRisk.java
  engine/src/main/java/app/dassana/core/risk/model/Risk.java
  engine/src/main/java/app/dassana/core/risk/model/RiskConfig.java
  engine/src/main/java/app/dassana/core/risk/model/Rule.java
  engine/src/main/java/app/dassana/core/rule/Behavior.java
  engine/src/main/java/app/dassana/core/rule/JsonQuery.java
  engine/src/main/java/app/dassana/core/rule/RuleMatchingException.java
  engine/src/main/java/app/dassana/core/workflow/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/main/java/app/dassana/core/workflow/model/WorkflowOutputWithRisk.java
  engine/src/test/java/app/dassana/core/launch/ApiTest.java
Labels: enhancement

#53 feat: resource contextualization. closes #48
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/Normalize.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/java/app/dassana/resourceid/sh/AppTest.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/resources/example1.json
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/App.java
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/Dassana.java
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/ProcessAlert.java
  content/actions/securityhub-update-finding/src/test/java/jar/AppTest.java
  content/actions/securityhub-update-finding/src/test/resources/sampleFinding.json
  content/schemas/dassana-vendor.yaml
  content/workflows/csp/aws/general-context/general-context.yaml
  content/workflows/csp/aws/service/cloudfront/resources/distribution/policy-context/root-object-is-not-configured.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-has-at-least-one-multi-region.yaml
  content/workflows/csp/aws/service/ec2/resources/flow-log/policy-context/vpc-flow-logs-are-disabled.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/instance-is-exposed-to-internet.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/snapshot/policy-context/ebs-snapshot-is-public.yaml
  content/workflows/csp/aws/service/ec2/resources/volume/policy-context/ebs-volume-is-not-encrypted.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-does-not-have-http-redirection.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-drop-http-headers.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/elb-tls-is-misconfigured.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/load-balancer-logging-is-not-enabled.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-policy-with-admin-access.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-support-role-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/access-key-is-not-rotated-frequently.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/hardware-mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-password-policy-is-not-secure.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-unused-credential-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-user-policy-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-for-iam-users.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/root-user-access-key-exists.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-public.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-public.yaml
  content/workflows/csp/aws/service/redshift/resources/cluster/policy-context/redshift-cluster-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-not-encrypted.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/requests-do-not-use-ssl.yaml
  content/workflows/vendors/security-hub/aws-config.yaml
  docs-root/docs/guides/vendor-setup/adding-vendors.mdx
  docs-root/docs/guides/workflow-authoring/policy-context.mdx
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/Handler.java
  engine/src/main/java/app/dassana/core/launch/model/Request.java
  engine/src/main/java/app/dassana/core/resource/model/ResourceContext.java
  engine/src/main/java/app/dassana/core/risk/model/CombinedRisk.java
  engine/src/main/java/app/dassana/core/rule/RuleMatch.java
  engine/src/main/java/app/dassana/core/workflow/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/test/java/app/dassana/core/launch/ApiTest.java
Labels: feature

#56 fix: use resource type from arn
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/App.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/DependencyFactory.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/Normalize.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/java/app/dassana/resourceid/sh/AppTest.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/resources/example1.json
Labels: bug

#63 Resource type fixes
  .dassana-internal-devops/public/vendor/aws-config/dark.png
  .dassana-internal-devops/public/vendor/aws-config/dark.svg
  .dassana-internal-devops/public/vendor/aws-config/light.png
  .dassana-internal-devops/public/vendor/aws-config/light.svg
  .dassana-internal-devops/scripts/policies.sh
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/App.java
  content/actions/gd-via-sh/src/test/java/app/dassana/actions/AppTest.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/Normalize.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/java/app/dassana/resourceid/sh/AppTest.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/resources/example2.json
  content/actions/what-enis-are-attached-to-sg/input.json
  content/actions/what-enis-are-attached-to-sg/src/handler.py
  content/actions/what-enis-are-attached-to-sg/src/test_handler.py
  content/pkg/deps/python/dassana/common/aws_client.py
  content/schemas/dassana-general-context.yaml
  content/schemas/dassana-policy-context.yaml
  content/schemas/dassana-resource-context.yaml
  content/workflows/csp/aws/general-context/general-context.yaml
  content/workflows/csp/aws/service/cloudfront/resources/distribution/policy-context/root-object-is-not-configured.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-has-at-least-one-multi-region.yaml
  content/workflows/csp/aws/service/ec2/resources/flow-log/policy-context/vpc-flow-logs-are-disabled.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/instance-is-exposed-to-internet.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/snapshot/policy-context/ebs-snapshot-is-public.yaml
  content/workflows/csp/aws/service/ec2/resources/volume/policy-context/ebs-volume-is-not-encrypted.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-does-not-have-http-redirection.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-drop-http-headers.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/elb-tls-is-misconfigured.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/load-balancer-logging-is-not-enabled.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-policy-with-admin-access.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-role-not-enabled-for-ec2.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-support-role-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/access-key-is-not-rotated-frequently.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/hardware-mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-password-policy-is-not-secure.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-unused-credential-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-user-policy-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-for-iam-users.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/root-user-access-key-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/user-has-console-and-access-keys.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-public.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-public.yaml
  content/workflows/csp/aws/service/redshift/resources/cluster/policy-context/redshift-cluster-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-not-encrypted.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/requests-do-not-use-ssl.yaml
  content/workflows/csp/demo-cloud/general-context/demo-cloud-service.yaml
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/resource/model/GeneralContext.java
  engine/src/main/java/app/dassana/core/resource/model/ResourceContext.java
  engine/src/main/java/app/dassana/core/workflow/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/infra/LambdaStepRunner.java
Labels: enhancement

#72 fix: lint content dir name
  .github/workflows/lint-content.yaml
Labels: bug

#74 Make DassanaEngineRole more restrictive
  content/pkg/template.yaml
Labels: enhancement

#76 fix: Update sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
Labels: bug

#78 Update sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
Labels: bug

#84 cleanup: remove policies field as root
  .dassana-internal-devops/scripts/policies.sh
Labels: chore

#77 Cis v1.2 logging network
  content/schemas/dassana-policy-context.yaml
  content/schemas/dassana-resource-context.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-encryption-not-enabled.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-is-not-configured-for-all-regions.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudwatch-logs-not-enabled.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/logs-validation-not-enabled-in-all-regions.yaml
  content/workflows/csp/aws/service/config/resources/config-recorder/config-recording-not-enabled.yaml
  content/workflows/csp/aws/service/ec2/resources/route-table/policy-context/vpc-route-table-is-overly-permissive.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/user-has-console-and-access-keys.yaml
  content/workflows/csp/aws/service/kms/resources/cmk/policy-context/cmk-rotation-not-enabled.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-logging-not-enabled.yaml
Labels: feature

#92 21
  content/pkg/deps/python/dassana/common/aws_client.py
  content/pkg/template.yaml
  content/workflows/vendors/foo-cloud/normalize.yaml
  engine/README.md
  engine/local-sam-env.json
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManagerApi.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/App.java
  engine/src/main/java/app/dassana/core/launch/Handler.java
  engine/src/main/java/app/dassana/core/launch/model/Request.java
  engine/src/main/java/app/dassana/core/launch/model/ValidationResult.java
  engine/src/main/java/app/dassana/core/launch/model/WorkflowNotFundException.java
  engine/src/main/java/app/dassana/core/launch/model/severity.java
  engine/src/main/java/app/dassana/core/policycontext/model/PolicyContext.java
  engine/src/main/java/app/dassana/core/rule/RuleMatch.java
  engine/src/main/java/app/dassana/core/util/JsonyThings.java
  engine/src/main/java/app/dassana/core/util/StringyThings.java
  engine/src/main/java/app/dassana/core/workflow/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/main/resources/TestEvent.json
  engine/src/test/java/app/dassana/core/launch/ApiTest.java
  engine/src/test/java/app/dassana/core/launch/Helper.java
  engine/src/test/java/app/dassana/core/util/StringyThingsTest.java
  engine/src/test/resources/inputs/validAlertWithDraftWorkflow.json
  engine/src/test/resources/inputs/validAlertWithNoGeneralContext.json
  engine/src/test/resources/inputs/validSecurityHubAlert.json
  engine/src/test/resources/responses/just-normalization.json
  engine/src/test/resources/validationRequests/invalidWorkflowType.json
  engine/src/test/resources/validationRequests/invalidWorkflowYaml.json
  engine/src/test/resources/validationRequests/validWorkflow.json
  engine/src/test/resources/validationRequests/validWorkflowButWithInvalidRule.json
Labels: feature

#94 21
  .github/release-drafter.yml
  .github/workflows/post-merge-to-main-release.yaml
  .github/workflows/publish-cft.yaml
  content/pkg/template.yaml
  engine/pom.xml
  engine/src/main/java/app/dassana/core/api/PingHandler.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/App.java
  engine/src/main/java/app/dassana/core/launch/model/PingResponse.java
Labels: feature

#95 Update test exclusions
  engine/pom.xml
Labels: chore

#97 Fix HTTP connection close stream issue
  engine/src/main/java/app/dassana/core/api/PingHandler.java
Labels: bug

#98 Bugfix - stream handling
  engine/src/main/java/app/dassana/core/api/PingHandler.java
Labels: bug

#101 use AHC
  engine/pom.xml
  engine/src/main/java/app/dassana/core/api/PingHandler.java
Labels: bug

#109 Add support for incident class
  .dassana-internal-devops/README.md
  .github/workflows/lint-content.yaml
  content/schemas/categories.yaml
  content/schemas/dassana-policy-context.yaml
  content/schemas/dassana-vendor.yaml
  content/schemas/policy-classification.yaml
  content/workflows/csp/aws/general-context/general-context.yaml
  content/workflows/csp/aws/service/cloudfront/resources/distribution/policy-context/root-object-is-not-configured.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-encryption-not-enabled.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-is-not-configured-for-all-regions.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudwatch-logs-not-enabled.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/logs-validation-not-enabled-in-all-regions.yaml
  content/workflows/csp/aws/service/config/resources/config-recorder/config-recording-not-enabled.yaml
  content/workflows/csp/aws/service/ec2/resources/flow-log/policy-context/vpc-flow-logs-are-disabled.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/instance-is-exposed-to-internet.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
  content/workflows/csp/aws/service/ec2/resources/route-table/policy-context/vpc-route-table-is-overly-permissive.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/snapshot/policy-context/ebs-snapshot-is-public.yaml
  content/workflows/csp/aws/service/ec2/resources/volume/policy-context/ebs-volume-is-not-encrypted.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-does-not-have-http-redirection.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-drop-http-headers.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/elb-tls-is-misconfigured.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/load-balancer-logging-is-not-enabled.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-policy-with-admin-access.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-role-not-enabled-for-ec2.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-support-role-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/access-key-is-not-rotated-frequently.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/hardware-mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-password-policy-is-not-secure.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-unused-credential-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-user-policy-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-for-iam-users.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/root-user-access-key-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/user-has-console-and-access-keys.yaml
  content/workflows/csp/aws/service/kms/resources/cmk/policy-context/cmk-rotation-not-enabled.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-public.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-public.yaml
  content/workflows/csp/aws/service/redshift/resources/cluster/policy-context/redshift-cluster-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-not-encrypted.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-logging-not-enabled.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/requests-do-not-use-ssl.yaml
  content/workflows/csp/demo-cloud/general-context/demo-cloud-service.yaml
  content/workflows/vendors/foo-cloud/normalize.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
  content/workflows/vendors/security-hub/aws-config.yaml
  content/workflows/vendors/security-hub/guardduty.yaml
  docs-root/docs/guides/workflow-authoring/policy-context.mdx
Labels: enhancement

#111 Add vendor list and icons to content directory + remove yamale vendor dep
  .dassana-internal-devops/README.md
  .github/workflows/lint-content.yaml
  content/schemas/dassana-policy-context.yaml
  content/schemas/dassana-vendor.yaml
  content/schemas/vendors/icons/aws-config.svg
  content/schemas/vendors/icons/foo-cloud.svg
  content/schemas/vendors/icons/guardduty.svg
  content/schemas/vendors/icons/prisma-cloud.svg
  content/schemas/vendors/vendor-list.yaml
  content/workflows/vendors/foo-cloud/normalize.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
  content/workflows/vendors/security-hub/aws-config.yaml
  content/workflows/vendors/security-hub/guardduty.yaml
  docs-root/docs/guides/workflow-authoring/normalize.mdx
Labels: enhancement

#116 Add linter to enforce correct policy classification #88
  content/schemas/policy-classification.yaml
  content/schemas/policy-classification/icons/categories/authentication.svg
  content/schemas/policy-classification/icons/categories/cryptography.svg
  content/schemas/policy-classification/icons/categories/iam.svg
  content/schemas/policy-classification/icons/categories/networking.svg
  content/schemas/policy-classification/icons/categories/visibility.svg
  content/schemas/policy-classification/icons/subcategories/alerting.svg
  content/schemas/policy-classification/icons/subcategories/authentication.svg
  content/schemas/policy-classification/icons/subcategories/encryption.svg
  content/schemas/policy-classification/icons/subcategories/firewall.svg
  content/schemas/policy-classification/icons/subcategories/logging.svg
  content/schemas/policy-classification/icons/subcategories/monitoring.svg
  content/schemas/policy-classification/icons/subcategories/public-access.svg
  content/schemas/policy-classification/icons/subcategories/ssl.svg
  content/schemas/policy-classification/policy-classification.yaml
  content/workflows/csp/aws/service/kms/resources/cmk/policy-context/cmk-rotation-not-enabled.yaml
  engine/src/main/java/app/dassana/core/api/DeepValidator.java
  engine/src/main/java/app/dassana/core/util/PolicyValidator.java
  engine/src/test/java/app/dassana/core/DeepValidator.java
Labels: feature

#100 feat: Ec2 exposure action
  content/actions/what-is-exposure-of-ec2-instance/README.md
  content/actions/what-is-exposure-of-ec2-instance/dassana-action.yaml
  content/actions/what-is-exposure-of-ec2-instance/input.json
  content/actions/what-is-exposure-of-ec2-instance/requirements.txt
  content/actions/what-is-exposure-of-ec2-instance/src/handler.py
  content/actions/what-is-exposure-of-ec2-instance/src/test_handler.py
  content/pkg/build.sh
  content/pkg/deps/python/dassana/common/aws_client.py
  content/pkg/template.yaml
Labels: feature

#120 Return step output when a requested workflow is run
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
Labels: bug

#119 feat: Website context action
  content/actions/website-context/input.json
  content/actions/website-context/src/handler.py
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/policies/csp/aws/service/s3/resources/bucket/bucket-has-broad-access-permissions.yaml
Labels: feature

#122 a bunch of normalization and api related fixes
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/Normalize.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/java/app/dassana/resourceid/sh/AppTest.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/resources/example3.json
  engine/src/main/java/app/dassana/core/workflow/RequestProcessor.java
  engine/src/test/java/app/dassana/core/rule/RuleMatchTest.java
Labels: bug

#121 cleanup: Actions cleanup
  content/actions/does-nacl-allow-traffic-from-internet/README.md
  content/actions/does-nacl-allow-traffic-from-internet/input.json
  content/actions/does-nacl-allow-traffic-from-internet/src/handler.py
  content/actions/does-sg-allow-incoming-connections-from-internet/input.json
  content/actions/does-sg-allow-incoming-connections-from-internet/requirements.txt
  content/actions/does-sg-allow-incoming-connections-from-internet/src/handler.py
  content/actions/is-autoscaling-group-tracking-target-group/README.md
  content/actions/is-autoscaling-group-tracking-target-group/dassana-action.yaml
  content/actions/is-autoscaling-group-tracking-target-group/input.json
  content/actions/is-autoscaling-group-tracking-target-group/requirements.txt
  content/actions/is-autoscaling-group-tracking-target-group/src/handler.py
  content/actions/is-eni-attached-to-instance/README.md
  content/actions/is-eni-attached-to-instance/dassana-action.yaml
  content/actions/is-eni-attached-to-instance/input.json
  content/actions/is-eni-attached-to-instance/requirements.txt
  content/actions/is-eni-attached-to-instance/src/handler.py
  content/actions/is-instance-part-of-autoscaling-group/README.md
  content/actions/is-instance-part-of-autoscaling-group/dassana-action.yaml
  content/actions/is-instance-part-of-autoscaling-group/input.json
  content/actions/is-instance-part-of-autoscaling-group/requirements.txt
  content/actions/is-instance-part-of-autoscaling-group/src/handler.py
  content/actions/is-load-balancer-internal/README.md
  content/actions/is-load-balancer-internal/dassana-action.yaml
  content/actions/is-load-balancer-internal/input.json
  content/actions/is-load-balancer-internal/requirements.txt
  content/actions/is-load-balancer-internal/src/handler.py
  content/actions/is-target-group-part-of-load-balancer/README.md
  content/actions/is-target-group-part-of-load-balancer/dassana-action.yaml
  content/actions/is-target-group-part-of-load-balancer/input.json
  content/actions/is-target-group-part-of-load-balancer/requirements.txt
  content/actions/is-target-group-part-of-load-balancer/src/handler.py
  content/actions/is-the-instance-behind-load-balancer/README.md
  content/actions/is-the-instance-behind-load-balancer/dassana-action.yaml
  content/actions/is-the-instance-behind-load-balancer/input.json
  content/actions/is-the-instance-behind-load-balancer/requirements.txt
  content/actions/is-the-instance-behind-load-balancer/src/handler.py
  content/actions/website-context/README.md
  content/actions/website-context/src/handler.py
  content/pkg/template.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/policies/csp/aws/service/s3/resources/bucket/bucket-has-broad-access-permissions.yaml
Labels: chore

#131 chore: refactor large classes
  content/pkg/template.yaml
  engine/pom.xml
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/SqsHandler.java
  engine/src/main/java/app/dassana/core/launch/model/ProcessingResponse.java
  engine/src/main/java/app/dassana/core/launch/model/Request.java
  engine/src/main/java/app/dassana/core/workflow/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/main/java/app/dassana/core/workflow/model/WorkflowException.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
  engine/src/main/java/app/dassana/core/workflow/processor/PostProcessor.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/processor/S3Manager.java
  engine/src/test/java/app/dassana/core/launch/ApiSqsHandlerTest.java
Labels: chore

#132 cleanup: remove prisma vendor
  content/actions/prisma-cloud-normalizer/README.md
  content/actions/prisma-cloud-normalizer/dassana-action.yaml
  content/actions/prisma-cloud-normalizer/input.json
  content/actions/prisma-cloud-normalizer/requirements.txt
  content/actions/prisma-cloud-normalizer/src/handler.py
  content/schemas/vendors/vendor-list.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-encryption-not-enabled.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudtrail-is-not-configured-for-all-regions.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloudwatch-logs-not-enabled.yaml
  content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/logs-validation-not-enabled-in-all-regions.yaml
  content/workflows/csp/aws/service/config/resources/config-recorder/config-recording-not-enabled.yaml
  content/workflows/csp/aws/service/ec2/resources/flow-log/policy-context/vpc-flow-logs-are-disabled.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/instance-is-exposed-to-internet.yaml
  content/workflows/csp/aws/service/ec2/resources/route-table/policy-context/vpc-route-table-is-overly-permissive.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/snapshot/policy-context/ebs-snapshot-is-public.yaml
  content/workflows/csp/aws/service/ec2/resources/volume/policy-context/ebs-volume-is-not-encrypted.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-does-not-have-http-redirection.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/elb-tls-is-misconfigured.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/load-balancer-logging-is-not-enabled.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-policy-with-admin-access.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-role-not-enabled-for-ec2.yaml
  content/workflows/csp/aws/service/iam/resources/policy/policy-context/iam-support-role-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/access-key-is-not-rotated-frequently.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/hardware-mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-password-policy-is-not-secure.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-unused-credential-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/iam-user-policy-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-for-iam-users.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/mfa-disabled-on-root-account.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/root-user-access-key-exists.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/user-has-console-and-access-keys.yaml
  content/workflows/csp/aws/service/kms/resources/cmk/policy-context/cmk-rotation-not-enabled.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-public.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-not-encrypted.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-not-encrypted.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-is-public.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-logging-not-enabled.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/requests-do-not-use-ssl.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: chore

#133 cleanup: remove redshift-cluster-is-public.yaml
  content/workflows/csp/aws/service/redshift/resources/cluster/policy-context/redshift-cluster-is-public.yaml
Labels: chore

#134 Deleted unused actions
  content/actions/does-nacl-allow-traffic-from-internet/README.md
  content/actions/does-nacl-allow-traffic-from-internet/dassana-action.yaml
  content/actions/does-nacl-allow-traffic-from-internet/input.json
  content/actions/does-nacl-allow-traffic-from-internet/requirements.txt
  content/actions/does-nacl-allow-traffic-from-internet/src/handler.py
  content/actions/does-sg-allow-incoming-connections-from-internet/README.md
  content/actions/does-sg-allow-incoming-connections-from-internet/dassana-action.yaml
  content/actions/does-sg-allow-incoming-connections-from-internet/input.json
  content/actions/does-sg-allow-incoming-connections-from-internet/requirements.txt
  content/actions/does-sg-allow-incoming-connections-from-internet/src/handler.py
  content/actions/which-subnets-are-associated-with-loadbalancer/README.md
  content/actions/which-subnets-are-associated-with-loadbalancer/dassana-action.yaml
  content/actions/which-subnets-are-associated-with-loadbalancer/input.json
  content/actions/which-subnets-are-associated-with-loadbalancer/requirements.txt
  content/actions/which-subnets-are-associated-with-loadbalancer/src/handler.py
  content/pkg/template.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
Labels: chore

#136 bunch of fixes for content handling
  content/pkg/build.sh
  content/pkg/template.yaml
  engine/src/main/java/app/dassana/core/api/PingHandler.java
  engine/src/main/java/app/dassana/core/api/VersionHandler.java
  engine/src/main/java/app/dassana/core/api/VersionResponse.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManagerApi.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/App.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
  engine/src/main/java/app/dassana/core/workflow/processor/PostProcessor.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/processor/S3Manager.java
  engine/src/test/java/app/dassana/core/launch/ApiSqsHandlerTest.java
Labels: bug

#137 Fix: handle json objects referenced within steps
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
Labels: bug

#138 fix- general context step output were missing
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
Labels: bug

#149 Bunch of doc related updates
  docs-root/blog/2021-08-30-s3-website.md
  docs-root/docs/common-fields/schema.md
  docs-root/docs/common-fields/workflows/filters.md
  docs-root/docs/common-fields/workflows/output.md
  docs-root/docs/common-fields/workflows/risk-config.mdx
  docs-root/docs/common-fields/workflows/rule-syntax.md
  docs-root/docs/getting-started/aws-cross-account-role.md
  docs-root/docs/getting-started/hello-world.mdx
  docs-root/docs/getting-started/installation.mdx
  docs-root/docs/guides/vendor-setup/aws-config/setup.md
  docs-root/docs/guides/workflow-authoring/execution.md
  docs-root/docs/guides/workflow-authoring/general-context.mdx
  docs-root/docs/guides/workflow-authoring/normalize.mdx
  docs-root/docs/guides/workflow-authoring/policy-context.mdx
  docs-root/docs/guides/workflow-authoring/resource-context.mdx
  docs-root/docs/how-it-works/low-level.mdx
  docs-root/docs/intro.md
  docs-root/package-lock.json
  docs-root/sidebars.js
  docs-root/static/img/guides/authoring/engine-execution.svg
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
Labels: documentation

#150 Update execution.md
  docs-root/docs/common-fields/workflows/filters.md
  docs-root/docs/common-fields/workflows/output.md
  docs-root/docs/common-fields/workflows/risk-config.mdx
  docs-root/docs/getting-started/hello-world.mdx
  docs-root/docs/getting-started/installation.mdx
  docs-root/docs/guides/action-authoring/action.mdx
  docs-root/docs/guides/vendor-setup/adding-vendors.mdx
  docs-root/docs/guides/vendor-setup/aws-config/setup.md
  docs-root/docs/guides/vendor-setup/guardduty/setup.md
  docs-root/docs/guides/workflow-authoring/editor.mdx
  docs-root/docs/guides/workflow-authoring/execution.md
  docs-root/docs/guides/workflow-authoring/general-context.mdx
  docs-root/docs/guides/workflow-authoring/normalize.mdx
  docs-root/docs/guides/workflow-authoring/policy-context.mdx
  docs-root/docs/guides/workflow-authoring/resource-context.mdx
  docs-root/docs/how-it-works/high-level.md
  docs-root/docs/how-it-works/low-level.mdx
  docs-root/docs/how-it-works/mid-level.md
  docs-root/docs/intro.md
  docs-root/package-lock.json
  docs-root/src/theme/BlogPostPage/index.js
Labels: documentation

#151 Fix instance not found exception
  content/actions/what-is-exposure-of-ec2-instance/src/handler.py
Labels: bug

#152 Alvin ux21 patch 2
  content/schemas/policy-classification/icons/category/credential-access.svg
  content/schemas/policy-classification/icons/class/incident.svg
  content/schemas/policy-classification/icons/class/jummie.svg
  content/schemas/policy-classification/icons/class/risk.svg
  content/schemas/policy-classification/icons/subcategory/authorization.svg
  content/schemas/policy-classification/icons/subcategory/secrets.svg
  docs-root/static/img/how-it-works/content.png
  docs-root/static/img/how-it-works/workflows.png
Labels: enhancement

#155 Bugfix doc update
  content/actions/what-is-exposure-of-ec2-instance/README.md
  content/actions/what-is-exposure-of-ec2-instance/src/handler.py
  content/pkg/template.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/resource-context/instance-context.yaml
Labels: bug

#156 fix: better error handling on websitecontext
  content/actions/website-context/src/handler.py
Labels: bug

#157 fix: websitecontext policy
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
Labels: bug

#154 [BUG] - Docs: Missing space in tagline on mobile
  docs-root/package-lock.json
  docs-root/package.json
  docs-root/src/components/HomepageHeader.module.css
Labels: bug
