Repository dassana-io/dassana, pull requests merged in 2021-10, with the labels that each got.

#313 Guard duty normalizer enhancement
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/App.java
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/Normalize.java
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/Response.java
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/App.java
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/Dassana.java
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/ProcessAlert.java
  content/workflows/vendors/security-hub/guardduty.yaml
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
Labels: enhancement

#308 workflow api changes minus delete
  engine/src/main/java/app/dassana/core/api/VersionHandler.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/model/Request.java
  engine/src/main/java/app/dassana/core/launch/model/WorkflowNotFoundException.java
  engine/src/main/java/app/dassana/core/launch/model/WorkflowNotFundException.java
  engine/src/main/java/app/dassana/core/workflow/model/WorkflowResponse.java
  engine/src/main/resources/TestNormalizer.yaml
Labels: feature

#283 feat: Action cache as higher order function
  .DS_Store
  .github/workflows/action-unit-tests.yaml
  .gitignore
  content/actions/get-tags/src/handler.py
  content/actions/website-context/src/handler.py
  content/actions/what-enis-are-attached-to-sg/src/handler.py
  content/actions/what-is-ec2-role/src/handler.py
  content/actions/what-is-exposure-of-ec2-instance/src/handler.py
  content/actions/what-is-exposure-of-ec2-instance/src/test_handler.py
  content/pkg/deps/python/dassana/common/aws_client.py
  content/pkg/deps/python/dassana/common/cache.py
  content/pkg/deps/python/dassana/tests/test_cache.py
  content/pkg/deps/python/requirements.txt
  content/pkg/deps/python/requirements_dev.txt
  docs-root/docs/guides/action-authoring/action.mdx
Labels: feature

#324 #305 remove output queue from engine
  content/pkg/template.yaml
  content/workflows/vendors/security-hub/aws-config.yaml
  content/workflows/vendors/security-hub/guardduty.yaml
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/App.java
  engine/src/main/java/app/dassana/core/launch/SqsHandler.java
  engine/src/main/java/app/dassana/core/launch/model/Request.java
  engine/src/main/java/app/dassana/core/normalize/model/NormalizerWorkflow.java
  engine/src/main/java/app/dassana/core/risk/eval/RiskEvalException.java
  engine/src/main/java/app/dassana/core/risk/eval/RiskEvaluator.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/main/java/app/dassana/core/workflow/model/Component.java
  engine/src/main/java/app/dassana/core/workflow/model/Error.java
  engine/src/main/java/app/dassana/core/workflow/model/WorkflowOutputWithRisk.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
  engine/src/main/java/app/dassana/core/workflow/processor/EventBridgeHandler.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/main/resources/TestEvent.json
  engine/src/test/java/app/dassana/core/launch/ApiSqsHandlerTest.java
Labels: enhancement

#329 Prisma cloud rule update
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: bug

#340 enhancement: boolean for behindLoadBalancer
  content/actions/what-is-exposure-of-ec2-instance/src/exposure/__init__.py
  content/actions/what-is-exposure-of-ec2-instance/src/exposure/models.py
  content/actions/what-is-exposure-of-ec2-instance/src/handler.py
Labels: enhancement
