Repository dassana-io/dassana, pull requests merged in 2021-09, with the labels that each got.

#172 feat #167 - [Docs]: Add Dassana's custom 404 page for the docs
  docs-root/src/theme/NotFound/NotFound.module.css
  docs-root/src/theme/NotFound/index.tsx
Labels: feature

#170 Add specific permissions to workflows under .github/workflows
  .github/workflows/engine-unit-tests.yaml
  .github/workflows/lint-content.yaml
  .github/workflows/post-merge-to-main-release.yaml
  .github/workflows/promote-app.yaml
  .github/workflows/promote-static-site-content.yaml
  .github/workflows/publish-cft.yaml
  .github/workflows/publish-public-policies-and-actions.yaml
  .github/workflows/publish-ut-coverage.yaml
  .github/workflows/verify-labels.yaml
Labels: chore

#184 Prettier for workflows
  content/workflows/.prettierrc
  content/workflows/csp/aws/service/ec2/resources/route-table/policy-context/vpc-route-table-is-overly-permissive.yaml
  content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/sg-is-wide-open.yaml
  content/workflows/csp/aws/service/ec2/resources/snapshot/policy-context/ebs-snapshot-is-public.yaml
  content/workflows/csp/aws/service/ec2/resources/volume/policy-context/ebs-volume-is-not-encrypted.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/alb-drop-http-headers.yaml
  content/workflows/csp/aws/service/elasticloadbalancing/resources/loadbalancer/policy-context/elb-tls-is-misconfigured.yaml
  content/workflows/csp/aws/service/iam/resources/user/policy-context/user-has-console-and-access-keys.yaml
  content/workflows/csp/aws/service/kms/resources/cmk/policy-context/cmk-rotation-not-enabled.yaml
  content/workflows/csp/aws/service/rds/resources/instance/policy-context/rds-instance-is-public.yaml
  content/workflows/csp/aws/service/rds/resources/snapshot/policy-context/rds-snapshot-is-not-encrypted.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/bucket-has-broad-access-permissions.yaml
  content/workflows/csp/aws/service/s3/resources/bucket/policy-context/requests-do-not-use-ssl.yaml
Labels: chore

#187 cache reimplementation
  engine/pom.xml
  engine/src/main/java/app/dassana/core/api/WorkflowValidator.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManagerApi.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentReader.java
  engine/src/main/java/app/dassana/core/contentmanager/RemoteContentDownloadApi.java
  engine/src/main/java/app/dassana/core/contentmanager/RemoteWorkflows.java
  engine/src/main/java/app/dassana/core/contentmanager/infra/S3Downloader.java
  engine/src/main/java/app/dassana/core/contentmanager/model/SyncResult.java
  engine/src/main/java/app/dassana/core/contentmanager/model/WorkflowProcessingResult.java
  engine/src/main/java/app/dassana/core/launch/ApiHandler.java
  engine/src/main/java/app/dassana/core/launch/App.java
  engine/src/main/java/app/dassana/core/launch/model/Request.java
  engine/src/main/java/app/dassana/core/util/JsonyThings.java
  engine/src/main/java/app/dassana/core/util/PolicyValidator.java
  engine/src/main/java/app/dassana/core/workflow/WorkflowRunner.java
  engine/src/main/java/app/dassana/core/workflow/model/Workflow.java
  engine/src/main/java/app/dassana/core/workflow/model/WorkflowOutputWithRisk.java
  engine/src/main/java/app/dassana/core/workflow/processor/Decorator.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/main/java/app/dassana/core/workflow/processor/S3Manager.java
  engine/src/main/resources/logback.xml
  engine/src/test/java/app/dassana/core/api/WorkflowValidatorTest.java
  engine/src/test/java/app/dassana/core/launch/ApiSqsHandlerTest.java
  engine/src/test/resources/inputs/validAlertWithDraftWorkflow.json
Labels: feature

#186 feat: autogen resource hierarchy artifact
  content/schemas/resource-hierarchy/resource-hierarchy.yaml
Labels: enhancement

#204 switched versionhandler from git repo to latest cft #192
  engine/pom.xml
  engine/src/main/java/app/dassana/core/api/VersionHandler.java
  engine/src/main/java/app/dassana/core/util/JsonyThings.java
Labels: bug

#205 fix: Lookup fix
  content/actions/normalizer-lookup/src/handler.py
  content/pkg/deps/python/dassana/common/models.py
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: bug

#206 Use LookUp action in AWS Config and Guard Duty
  content/actions/README.md
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/App.java
  content/actions/gd-via-sh/src/main/java/app/dassana/actions/Response.java
  content/actions/gd-via-sh/src/test/java/app/dassana/actions/AppTest.java
  content/actions/normalizer-lookup/src/handler.py
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/NormalizationResult.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/Normalize.java
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/test/java/app/dassana/resourceid/sh/AppTest.java
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/instance-is-exposed-to-internet.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/ssh-bruteforce.yaml
  content/workflows/vendors/security-hub/aws-config.yaml
  content/workflows/vendors/security-hub/guardduty.yaml
  engine/src/test/resources/responses/badNormalizer.json
  engine/src/test/resources/responses/normalization.json
Labels: bug

#210 fix: change jq convention to "name" for tags
  content/workflows/csp/aws/general-context/general-context.yaml
  engine/src/test/resources/responses/tags.json
Labels: bug

#211 fix: remove csp mutation
  content/actions/normalizer-lookup/src/handler.py
  content/workflows/csp/aws/service/ec2/resources/snapshot/policy-context/ebs-snapshot-not-encrypted.yaml
Labels: bug

#213 Alvin ux21 patch 2
  docs-root/static/img/guides/authoring/engine-execution.svg
Labels: chore

#219 feat: Get tags Python implementation
  content/actions/get-tags/README.md
  content/actions/get-tags/input.json
  content/actions/get-tags/src/handler.py
  content/actions/get-tags/src/main/java/app/dassana/action/App.java
  content/actions/get-tags/src/main/java/app/dassana/action/Tag.java
  content/actions/get-tags/src/test/java/app/dassana/action/AppTest.java
  content/pkg/deps/python/dassana/common/models.py
  content/pkg/template.yaml
Labels: feature

#220 refactor: remove s3 condition and use default region for tagging api
  content/actions/get-tags/input.json
  content/actions/get-tags/src/handler.py
Labels: chore

#215 feat: EC2 role action
  content/actions/what-is-ec2-role/README.md
  content/actions/what-is-ec2-role/dassana-action.yaml
  content/actions/what-is-ec2-role/input.json
  content/actions/what-is-ec2-role/requirements.txt
  content/actions/what-is-ec2-role/src/handler.py
  content/pkg/template.yaml
Labels: feature

#222 Clean up + fix typos in classification docs
  docs-root/docs/guides/classification/policy.mdx
  docs-root/docs/guides/classification/resource-hierarchy.mdx
  docs-root/docs/guides/valid-structure/policy-fields.mdx
  docs-root/docs/guides/valid-structure/resource-fields.mdx
  docs-root/sidebars.js
  engine/src/main/java/app/dassana/core/api/linter/BaseLinter.java
Labels: documentation

#223 fix typos in introduction
  docs-root/docs/intro.md
Labels: chore

#234 Fixed broken build
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
  content/workflows/vendors/security-hub/aws-config.yaml
Labels: bug

#214 Alvin ux21 patch 2
  docs-root/static/img/guides/authoring/engine-execution.svg
Labels: enhancement

#236 fix- sqs handling
  content/pkg/template.yaml
  engine/src/main/java/app/dassana/core/launch/SqsHandler.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
Labels: bug

#237 Update docs theme
  docs-root/docusaurus.config.js
Labels: chore

#238 fix: Revise model for new Prisma Cloud alert schema
  content/actions/prisma-cloud-normalizer/src/handler.py
Labels: bug

#242 Replaced duplicate joke with a new one.
  engine/src/main/java/app/dassana/core/api/PingHandler.java
Labels: chore

#243 made resource-type and service optional in normalizer
  engine/src/main/java/app/dassana/core/api/linter/CommonLinter.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
Labels: enhancement

#246 Update prisma-cloud.yaml
  content/workflows/csp/aws/general-context/general-context.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
  engine/src/main/java/app/dassana/core/workflow/processor/S3Manager.java
Labels: bug

#250 Fix stale references
  docs-root/blog/2021-08-30-s3-website.md
  docs-root/docs/guides/classification/policy.mdx
Labels: chore

#257 Prisma Cloud article
  docs-root/blog/2021-09-20-prisma-cloud.md
  docs-root/static/img/blog/prisma-cloud/categorizedAlerts.png
  docs-root/static/img/blog/prisma-cloud/dassanaLovesPrismaCloud.jpg
  docs-root/static/img/blog/prisma-cloud/finalAlerts.png
  docs-root/static/img/blog/prisma-cloud/integration.jpg
  docs-root/static/img/blog/prisma-cloud/regionAlerts.png
  docs-root/static/img/blog/prisma-cloud/splunkDashboard.png
  docs-root/static/img/blog/prisma-cloud/totalAlerts.png
Labels: documentation

#271 closes #270
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/normalize/model/NormalizerWorkflow.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/test/java/app/dassana/core/launch/ApiSqsHandlerTest.java
  engine/src/test/resources/inputs/validWorkflowWithOnlyNormalization.json
Labels: feature

#272 Bring back execution docs
  docs-root/sidebars.js
Labels: bug

#278 Implement eventbridge
  content/pkg/template.yaml
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
  engine/pom.xml
  engine/src/main/java/app/dassana/core/client/infra/Factories.java
  engine/src/main/java/app/dassana/core/contentmanager/ContentManager.java
  engine/src/main/java/app/dassana/core/normalize/model/NormalizerWorkflow.java
  engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java
  engine/src/test/java/app/dassana/core/launch/MockClients.java
Labels: feature

#280 feat: optimizing lookup
  content/actions/normalizer-lookup/src/handler.py
Labels: feature

#284 SH Normalizer Raw alert support
  content/actions/security-hub-normalizer/impl/sh-resourceid-extractor/src/main/java/app/dassana/resourceid/sh/Normalize.java
  content/actions/securityhub-update-finding/src/main/java/app/dassana/action/App.java
  content/workflows/vendors/security-hub/aws-config.yaml
Labels: enhancement

#293 API Gateway + ACM + Cloudformation
  content/workflows/csp/aws/service/apiGateway/resources/Authorizer/policy-context/api-gateway-endpoints-without-client-certificate-authentication.yaml
  content/workflows/csp/aws/service/apiGateway/resources/Authorizer/policy-context/api-gateway-request-authorization-is-not-set.yaml
  content/workflows/csp/aws/service/apiGateway/resources/RequestValidator/policy-context/api-gateway-request-parameter-is-not-validated.yaml
  content/workflows/csp/aws/service/apiGateway/resources/RestApis/policy-context/api-gateway-does-not-match-endpoint-type-config.yaml
  content/workflows/csp/aws/service/apiGateway/resources/RestApis/policy-context/api-gateway-xray-is-not-enabled.yaml
  content/workflows/csp/aws/service/apiGateway/resources/Stage/policy-context/api-gateway-execution-logging-is-not-enabled.yaml
  content/workflows/csp/aws/service/apiGateway/resources/Stage/policy-context/api-gateway-ssl-is-not-enabled.yaml
  content/workflows/csp/aws/service/apiGateway/resources/Stages/policy-context/api-gateway-is-not-cache-enabled-and-encrypted.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/acm-certificate-has-issues.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/acm-certificate-with-wildcard-domain-name.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/acm-has-certificates-with-certificate-transparency-logging-disabled.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/aws-certificate-manager-(acm)-contains-certificate-pending-validation.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/aws-certificate-manager-(acm)-has-expired-certificates.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/aws-certificate-manager-(acm)-has-invalid-or-failed-certificate.yaml
  content/workflows/csp/aws/service/certificateManager/resources/certificate/policy-context/aws-certificate-manager-(acm)-has-unused-certificates.yaml
  content/workflows/csp/aws/service/cloudformation/resources/stack/policy-context/cloudformation-stack-has-drifted.yaml
  content/workflows/csp/aws/service/cloudformation/resources/stack/policy-context/cloudformation-stack-is-configured-without-sns-topic.yaml
  content/workflows/csp/aws/service/cloudformation/resources/stack/policy-context/cloudformation-template-contains-globally-open-resources.yaml
  content/workflows/csp/aws/service/dms/resources/Certificate/policy-context/aws-database-migration-service-(dms)-has-expired-certificates.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/instance-is-using-security-group-not-attached-to-eni.yaml
  content/workflows/csp/aws/service/ec2/resources/instance/policy-context/managedinstance-is-not-running-required-application.yaml
Labels: chore

#306 feat: Prisma Cloud api and splunk normalizer support
  content/actions/prisma-cloud-normalizer/src/handler.py
  content/actions/prisma-cloud-normalizer/tests/data/prisma_api.json
  content/actions/prisma-cloud-normalizer/tests/data/prisma_splunk.json
  content/actions/prisma-cloud-normalizer/tests/data/prisma_sqs.json
  content/actions/prisma-cloud-normalizer/tests/test_handler.py
  content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
Labels: feature
